language: groovy
jdk:
- oraclejdk7
before_install:
- sudo apt-get -qq update
- sudo apt-get -qq -y install graphviz
- sudo pip install awscli
git:
  submodules: false
env:
  global:
  - _JAVA_OPTIONS='-Xverify:none -XX:MaxPermSize=256m'
  - GRADLE_OPTS='-Dorg.gradle.daemon=false'
after_script:
- bash pub-tests.sh build/reports/tests/ travis
